# Generated by Django 2.1.1 on 2018-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_auto_20180912_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historyAlert',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='user',
            name='threshold',
            field=models.FloatField(default=0),
        ),
    ]
