# Generated by Django 2.1.1 on 2018-09-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20180913_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='underThreshold',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='historyAlert',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='threshold',
            field=models.FloatField(default=0.5),
        ),
    ]
